server:
  port: 8080

mqtt:
  broker-uri: ${BROKER_URI:tcp://azat222.ru:1883}
  client-id: ${CLIENT_ID:fitocube-backend}
  command-topic: ${COMMAND_TOPIC:soil/cmd}
  data-topic: ${DATA_TOPIC:soil/data}
  command-payload: get_info
  response-timeout: 5s

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
